import {
  UserProfile,
  WalletState,
  JobShift,
  ChatContact,
  RecentActivity,
  AppNotification,
} from '@/types';

export const INITIAL_USER: UserProfile = {
  name: 'Alex Chen',
  role: 'Freelance Specialist & Shift Worker',
  userType: 'employee',
  avatar:
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  phone: '+91 98765 43210',
  email: 'alex.chen@parttime.io',
  upiId: 'alexchen@okaxis',
  age: 22,
  isAgeVerified: true,
  kycStatus: 'verified',
  kycIdType: 'Aadhaar Card (Verified)',
  kycDocNumber: '•••• •••• 8839',
  hourlyRateRange: { min: 250, max: 1200 },
  skills: [
    'Barista & Brewing',
    'Event Management',
    'Retail POS',
    'Photography',
    'Customer Care',
  ],
  activeOtp: '6767',
  completedGigsCount: 28,
  rating: 4.95,
};

export const INITIAL_WALLET: WalletState = {
  balance: 1000,
  currency: '₹',
  upiId: 'alexchen@okaxis',
  linkedBank: 'HDFC Bank •••• 4091',
  transactions: [
    {
      id: 'tx-101',
      title: "Akhila's Brew Lab - Evening Shift",
      category: 'Shift Payout',
      amount: 500,
      type: 'credit',
      date: 'Today, 11:30 AM',
      status: 'Completed',
      icon: 'coffee',
      badge: 'Shift Settlement',
    },
    {
      id: 'tx-102',
      title: 'UPI Transfer to GPay',
      category: 'Withdrawal',
      amount: 300,
      type: 'debit',
      date: 'Yesterday, 04:15 PM',
      status: 'Completed',
      icon: 'arrow-up-right',
      badge: 'GPay / UPI',
    },
    {
      id: 'tx-103',
      title: 'City Promo Flyer Distribution',
      category: 'Micro Shift',
      amount: 100,
      type: 'credit',
      date: 'Sep 12, 02:00 PM',
      status: 'Completed',
      icon: 'sparkles',
      badge: 'Micro Gig',
    },
    {
      id: 'tx-104',
      title: 'Weekend Tech Usher Bonus',
      category: 'Bonus Payout',
      amount: 700,
      type: 'credit',
      date: 'Sep 10, 08:45 PM',
      status: 'Completed',
      icon: 'award',
      badge: 'Bonus Payout',
    },
  ],
};

export const INITIAL_JOBS: JobShift[] = [
  {
    id: 'job-101',
    title: 'Express Flyer & Promo Distributor',
    employer: "Arun's Cafe & Roasters",
    employerAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    employerRating: 4.8,
    category: 'Promotion',
    wage: 100,
    wageUnit: 'per hour',
    duration: '2 Hours',
    timeSlot: 'Today, 4:00 PM - 6:00 PM',
    distanceKm: 0.8,
    location: 'Metro Station Exit 3, Indiranagar',
    coords: { x: 38, y: 46 },
    tags: ['Instant Payout', 'Urgent', 'No Exp Required'],
    description:
      'Distribute promotional tasting vouchers to evening commuters near the main gate. Friendly attitude required. Refreshments provided!',
    openSlots: 2,
    checkInPin: '6767',
    isUrgent: true,
    badgeColor: 'cyan',
  },
  {
    id: 'job-102',
    title: 'Artisan Coffee Barista & Counter',
    employer: "Akhila's Brew Lab",
    employerAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    employerRating: 4.9,
    category: 'Cafe',
    wage: 500,
    wageUnit: '4-hour shift',
    duration: '4 Hours',
    timeSlot: 'Today, 5:00 PM - 9:00 PM',
    distanceKm: 1.4,
    location: '12th Main Road, Koramangala 4th Block',
    coords: { x: 62, y: 32 },
    tags: ['Verified Employer', 'Meals Included', 'Tips Keep 100%'],
    description:
      'Assist our head barista during the busy evening peak hours. Espresso machine basics preferred. Friendly team environment.',
    openSlots: 1,
    checkInPin: '6767',
    isUrgent: false,
    badgeColor: 'amber',
  },
  {
    id: 'job-103',
    title: 'VIP Tech Summit Usher & Registration',
    employer: "Ryan's Media Con",
    employerAvatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    employerRating: 5.0,
    category: 'Events',
    wage: 1000,
    wageUnit: 'single day',
    duration: '6 Hours',
    timeSlot: 'Tomorrow, 9:00 AM - 3:00 PM',
    distanceKm: 2.8,
    location: 'Grand Convention Center, Hall B',
    coords: { x: 74, y: 68 },
    tags: ['Instant UPI', 'Certificate Provided', 'Free Lunch'],
    description:
      'Scan attendee QR passes, issue delegate badges, and guide VIP keynote speakers to the lounge. Formal smart casual dress code.',
    openSlots: 4,
    checkInPin: '6767',
    isUrgent: true,
    badgeColor: 'emerald',
  },
  {
    id: 'job-104',
    title: 'Weekend Expo Booth Coordinator',
    employer: 'Toby Logistics & Events',
    employerAvatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    employerRating: 4.9,
    category: 'Logistics',
    wage: 10000,
    wageUnit: 'weekend gig',
    duration: '2 Days (Sat - Sun)',
    timeSlot: 'Sat & Sun, 10:00 AM - 7:00 PM',
    distanceKm: 4.5,
    location: 'BIEC Exhibition Grounds, Pavilion 4',
    coords: { x: 22, y: 76 },
    tags: ['High Payout', 'Team Lead', 'Transport Included'],
    description:
      'Lead on-ground product demos, organize inventory restocking, and coordinate a 6-person brand ambassador team across the weekend trade show.',
    openSlots: 1,
    checkInPin: '6767',
    isUrgent: false,
    badgeColor: 'purple',
  },
  {
    id: 'job-105',
    title: 'Retail Merchandising & Display Assistant',
    employer: 'Urban Clothiers',
    employerAvatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    employerRating: 4.7,
    category: 'Retail',
    wage: 650,
    wageUnit: 'evening shift',
    duration: '5 Hours',
    timeSlot: 'Tonight, 6:00 PM - 11:00 PM',
    distanceKm: 1.9,
    location: 'Forum Mall, 2nd Floor, Whitefield',
    coords: { x: 80, y: 22 },
    tags: ['Staff Discount', 'AC Environment'],
    description:
      'Steam clothing, organize size racks, and maintain the front display window aesthetics during the weekend festive rush.',
    openSlots: 3,
    checkInPin: '6767',
    isUrgent: false,
    badgeColor: 'indigo',
  },
  {
    id: 'job-106',
    title: 'Rapid Dark Store Order Packer',
    employer: 'QuickBasket Express',
    employerAvatar:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    employerRating: 4.6,
    category: 'Delivery',
    wage: 450,
    wageUnit: '3-hour surge',
    duration: '3 Hours',
    timeSlot: 'Today, 7:00 PM - 10:00 PM',
    distanceKm: 1.1,
    location: 'Hub 9, BTM 2nd Stage',
    coords: { x: 45, y: 82 },
    tags: ['Surge Bonus', 'Performance Bonus'],
    description:
      'Pick and pack grocery basket orders under 5 minutes for dispatch riders. Fast-paced and fun warehouse environment.',
    openSlots: 5,
    checkInPin: '6767',
    isUrgent: true,
    badgeColor: 'rose',
  },
];

export const INITIAL_CHATS: ChatContact[] = [
  {
    id: 'chat-arun',
    contactName: 'Arun',
    role: 'Cafe Shift Manager',
    company: "Arun's Cafe & Roasters",
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    status: 'online',
    unreadCount: 1,
    lastMessageTime: '2m ago',
    jobReference: 'Express Flyer & Promo (₹100/hr)',
    messages: [
      {
        id: 'm1',
        sender: 'them',
        text: 'Hey Alex! Saw your profile. Are you available for the 4:00 PM distribution gig near Indiranagar?',
        time: '2:15 PM',
      },
      {
        id: 'm2',
        sender: 'me',
        text: 'Hi Arun! Yes, definitely available. I can be there by 3:50 PM.',
        time: '2:18 PM',
      },
      {
        id: 'm3',
        sender: 'them',
        text: 'Awesome! Please remember our check-in PIN code is 6767. See you soon!',
        time: '2:20 PM',
      },
    ],
  },
  {
    id: 'chat-akhila',
    contactName: 'Akhila',
    role: 'Head Roaster & Store Lead',
    company: "Akhila's Brew Lab",
    avatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    status: 'online',
    unreadCount: 0,
    lastMessageTime: '1h ago',
    jobReference: 'Artisan Coffee Barista (₹500/shift)',
    messages: [
      {
        id: 'm10',
        sender: 'them',
        text: 'Alex, great work on the pour-overs yesterday! The customer reviews were glowing.',
        time: 'Yesterday, 9:15 PM',
      },
      {
        id: 'm11',
        sender: 'me',
        text: 'Thank you Akhila! Loved the beans blend. Did the hours log correctly?',
        time: 'Yesterday, 9:20 PM',
      },
      {
        id: 'm12',
        sender: 'them',
        text: 'Yes, I approved your payout of ₹500 directly into your PART-TIME wallet just now!',
        time: '11:30 AM',
      },
    ],
  },
  {
    id: 'chat-ryan',
    contactName: 'Ryan',
    role: 'Event Operations Supervisor',
    company: "Ryan's Media Con",
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    status: 'away',
    unreadCount: 2,
    lastMessageTime: '3h ago',
    jobReference: 'VIP Tech Summit Usher (₹1,000/day)',
    messages: [
      {
        id: 'm20',
        sender: 'them',
        text: 'Hi Alex, you are confirmed for tomorrow\'s Tech Summit at Hall B.',
        time: '10:00 AM',
      },
      {
        id: 'm21',
        sender: 'them',
        text: 'Check-in at Gate 2 with your One-Time PIN 6767. Breakfast will be ready at 8:30 AM.',
        time: '10:02 AM',
      },
    ],
  },
  {
    id: 'chat-toby',
    contactName: 'Toby',
    role: 'Logistics Lead',
    company: 'Toby Logistics & Events',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    status: 'offline',
    unreadCount: 0,
    lastMessageTime: 'Yesterday',
    jobReference: 'Weekend Expo Coordinator (₹10,000/gig)',
    messages: [
      {
        id: 'm30',
        sender: 'them',
        text: 'Shift completed! Thanks for handling the inventory booth so smoothly last time.',
        time: 'Yesterday, 6:00 PM',
      },
      {
        id: 'm31',
        sender: 'me',
        text: 'Anytime Toby! Looking forward to the upcoming weekend expo.',
        time: 'Yesterday, 6:15 PM',
      },
    ],
  },
];

export const INITIAL_ACTIVITIES: RecentActivity[] = [
  {
    id: 'act-1',
    title: "Barista Shift - Akhila's Brew Lab",
    type: 'Completed Shift',
    wage: '₹500',
    date: 'Today, 11:30 AM',
    status: 'Settled',
    statusColor: 'emerald',
    pinUsed: '6767',
  },
  {
    id: 'act-2',
    title: 'VIP Tech Summit Usher',
    type: 'Application Accepted',
    wage: '₹1,000',
    date: 'Starts Tomorrow, 9:00 AM',
    status: 'Scheduled',
    statusColor: 'cyan',
    pinUsed: '6767',
  },
  {
    id: 'act-3',
    title: 'Flyer & Promo Distributor',
    type: 'Application Sent',
    wage: '₹100/hr',
    date: 'Today, 2:18 PM',
    status: 'Under Review',
    statusColor: 'amber',
    pinUsed: 'Pending',
  },
  {
    id: 'act-4',
    title: 'Weekend Expo Booth Lead',
    type: 'Completed Project',
    wage: '₹10,000',
    date: 'Sep 8, 2026',
    status: 'Settled',
    statusColor: 'emerald',
    pinUsed: '6767',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Payment Received! 💰',
    message: "₹500 credited to your wallet for Akhila's Brew Lab shift.",
    time: '25m ago',
    type: 'wallet',
    unread: true,
  },
  {
    id: 'notif-2',
    title: 'Shift Check-in PIN Active 🔑',
    message:
      "Your attendance PIN for today's shifts is 6767. Provide this to the employer on arrival.",
    time: '1h ago',
    type: 'security',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'Application Accepted! 🎉',
    message:
      "Ryan's Media Con accepted your application for Tech Summit Usher (₹1,000).",
    time: '3h ago',
    type: 'job',
    unread: false,
  },
  {
    id: 'notif-4',
    title: 'KYC Status: Verified ✅',
    message:
      'Your age (22 >= 18) and government ID have been successfully verified.',
    time: '1 day ago',
    type: 'kyc',
    unread: false,
  },
];
